In [4]:
import pandas as pd

df = pd.read_csv("/content/Top-100 Trending Books.csv")

In [5]:
df.head()

,Rank,book title,book price,rating,author,year of publication,genre,url
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...

In [10]:
#Row wise

subset1 = df.head(10)
subset2 = df[df['book price'] > 10]

In [8]:
subset1

,Rank,book title,book price,rating,author,year of publication,genre,url
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...
5,6,"Fourth Wing (The Empyrean, 1)",16.99,4.8,Rebecca Yarros,2023,Fantasy,amazon.com/Fourth-Wing-Empyrean-Rebecca-Yarros...
6,7,Unwoke: How to Defeat Cultural Marxism in America,27.43,4.3,Unknown,2023,"Nonfiction, Politics",amazon.com/Unwoke-Defeat-Cultural-Marxism-Amer...
7,8,No Brainer (Diary of a Wimpy Kid Book 18),8.55,4.8,Jeff Kinney,2023,"Humor, Middle Grade",amazon.com/Brainer-Diary-Wimpy-Kid-Book/dp/141...
8,9,Killers of the Flower Moon: The Osage Murders ...,9.86,4.4,David Grann,2017,"Nonfiction, True Crime",amazon.com/Killers-Flower-Moon-Osage-Murders/d...
9,10,All the Light We Cannot See: A Novel,11.98,4.5,Anthony Doerr,2014,Historical Fiction,amazon.com/All-Light-We-Cannot-See/dp/15011732...

In [11]:
subset2

,Rank,book title,book price,rating,author,year of publication,genre,url
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
5,6,"Fourth Wing (The Empyrean, 1)",16.99,4.8,Rebecca Yarros,2023,Fantasy,amazon.com/Fourth-Wing-Empyrean-Rebecca-Yarros...
6,7,Unwoke: How to Defeat Cultural Marxism in America,27.43,4.3,Unknown,2023,"Nonfiction, Politics",amazon.com/Unwoke-Defeat-Cultural-Marxism-Amer...
9,10,All the Light We Cannot See: A Novel,11.98,4.5,Anthony Doerr,2014,Historical Fiction,amazon.com/All-Light-We-Cannot-See/dp/15011732...
10,11,The Ballad of Songbirds and Snakes (A Hunger G...,10.99,4.6,Suzanne Collins,2020,"Adventure, War, Science fiction, Romance, Acti...",amazon.com/Ballad-Songbirds-Snakes-Hunger-Game...
12,13,Atomic Habits: An Easy & Proven Way to Build G...,13.79,4.8,James Clear,2018,"Self-improvement, Nonfiction",amazon.com/Atomic-Habits-Proven-Build-Break/dp...
14,15,The 48 Laws of Power,13.82,4.7,Robert Greene,1998,Nonfiction,amazon.com/48-Laws-Power-Robert-Greene/dp/0140...
15,16,The Great Disappearance: 31 Ways to be Rapture...,18.84,4.6,David Jeremiah,2023,"Spiritual Warfare, Biblical Studies - Prophecy...",amazon.com/Great-Disappearance-Ways-Rapture-Re...
16,17,Lessons in Chemistry: A Novel,15.37,4.6,Bonnie Garmus,2022,"Fiction, Historical Fiction",amazon.com/Lessons-Chemistry-Novel-Bonnie-Garm...
17,18,The Exchange: After The Firm (The Firm Series),18.96,4.1,John Grisham,2023,"Literary, Thrillers - Suspense",amazon.com/Exchange-After-Firm/dp/0385548958/r...
19,20,Don't Let the Pigeon Drive the Sleigh!,11.99,4.8,Mo Willems,2023,"Picture Books, Christmas, Holiday, Humor, Chil...",amazon.com/Dont-Let-Pigeon-Drive-Sleigh/dp/145...
23,24,A Little Life,11.83,4.5,Hanya Yanagihara,2015,"Fiction, Contemporary, LGBT, Literary Fiction,...",amazon.com/Little-Life-Hanya-Yanagihara/dp/080...
24,25,"House of Flame and Shadow (Crescent City, 3)",18.48,NaN,Sarah J. Maas,2023,"Fantasy, Dragons, Young Adult, Fiction, High F...",amazon.com/House-Flame-Shadow-Crescent-City/dp...
27,28,The Leaf Thief: (The Perfect Fall Book for Chi...,10.39,4.8,Alice Hemming,2021,Childrens,amazon.com/Leaf-Thief-Alice-Hemming/dp/1728235...
28,29,Murtagh: The World of Eragon (The Inheritance ...,22.48,4.8,Christopher Paolini,2023,"Fantasy, Dragons, Young Adult, Fiction, High F...",amazon.com/Murtagh-World-Eragon-Inheritance-Cy...
30,31,Balloons over Broadway: The True Story of the ...,12.19,4.9,Bill Martin Jr.,1967,"Childrens, literature",amazon.com/Balloons-over-Broadway-Puppeteer-Ed...
33,34,How to Know a Person: The Art of Seeing Others...,19.89,4.5,Alice Walstead,2022,"Thriller, mystery, suspense",amazon.com/How-Know-Person-Seeing-Others/dp/05...
37,38,The Psychology of Money: Timeless lessons on w...,12.68,4.7,Sandra Boynton,2022,"Picture Books, Childrens, Holiday",amazon.com/Psychology-Money-Timeless-lessons-h...
40,41,Outlive: The Science and Art of Longevity,16.99,4.7,Peter Attia,2023,"Health, Nonfiction, Science, Self Help",amazon.com/Outlive-Longevity-Peter-Attia-MD/dp...
41,42,Hundred Years' War on Palestine,12.99,4.6,Rashid Khalidi,2019,"History, Nonfiction, Politics, War",amazon.com/Hundred-Years-War-Palestine-Colonia...
42,43,Little Blue Truck's Christmas: A Christmas Hol...,11.20,4.8,Alice Schertle,2014,"Childrens, literature",amazon.com/Little-Trucks-Christmas-Alice-Scher...
45,46,"How to Be the Love You Seek: Break Cycles, Fin...",20.11,NaN,Nicole LePera,2023,"Self Help, Nonfiction, Mental Health, Psycholo...",amazon.com/How-Love-You-Seek-Relationships/dp/...
46,47,A Court of Thorns and Roses Paperback Box Set ...,48.77,4.8,Sarah J. Maas,2021,"Fantasy, Romance",amazon.com/Court-Thorns-Roses-Paperback-books/...
50,51,Hidden Potential: The Science of Achieving Gre...,21.00,4.4,Adam M. Grant,2023,"Nonfiction, Self Help, Psychology, Business, L...",amazon.com/Hidden-Potential-Science-Achieving-...
51,52,Resurrection Walk (Lincoln Lawyer),20.98,5.0,Michael Connelly,2023,"Fiction, Mystery, Thriller, Suspense, Crime, L...",amazon.com/Resurrection-Walk-Michael-Connelly/...
56,57,From Crook to Cook: Platinum Recipes from Tha ...,12.15,4.8,Snoop Dogg,2018,"Cookbooks, Cooking",amazon.com/Crook-Cook-Platinum-Recipes-Kitchen...
57,58,The Shadow Work Journal: A Guide to Integrate ...,17.28,4.6,Keila Shaheen,2021,"Self Help, Psychology",amazon.com/Shadow-Work-Journal-Integrate-Trans...
58,59,Interesting Facts For Curious Minds: 1572 Rand...,12.89,4.6,Jordan Moore,2022,Nonfiction,amazon.com/Interesting-Facts-Curious-Minds-Min...
60,61,Elon Musk,20.99,4.7,Walter Isaacson,2023,"Biography, Nonfiction, Business, Technology",amazon.com/Elon-Musk-Walter-Isaacson/dp/198218...
63,64,Tom Lake: A Reese's Book Club Pick,15.33,4.3,Ann Patchett,2023,"Literary, Medical, Family Life - General, Worl...",amazon.com/Tom-Lake-Novel-Ann-Patchett/dp/0063...
64,65,The Covenant of Water (Oprah's Book Club),16.79,4.6,Abraham Verghese,2023,"Fiction, Mystery",amazon.com/Covenant-Water-Abraham-Verghese/dp/...
65,66,Dirty Thirty (30) (Stephanie Plum),20.98,4.7,Janet Evanovich,2021,"Dark, Thriller, Fantasy, Adult, Contemporary, ...",amazon.com/Dirty-Thirty-30-Stephanie-Plum/dp/1...
69,70,Haunting Adeline (Cat and Mouse Duet),13.36,4.4,H.D. Carlton,2021,"Dark, Thriller, Fantasy, Adult, Contemporary, ...",amazon.com/Haunting-Adeline-Cat-Mouse-Duet/dp/...
70,71,Verity,10.98,4.6,Colleen Hoover,2018,"Thriller, Romance, Mystery, Fiction",amazon.com/Verity-Colleen-Hoover/dp/1538724731...
71,72,A Court of Mist and Fury (A Court of Thorns an...,12.79,4.8,Sarah J. Maas,2016,"Fantasy, Romance, Young Adult, New Adult, Fiction",amazon.com/Court-Mist-Fury-Thorns-Roses/dp/163...
72,73,The Creative Act: A Way of Being,17.49,4.7,Rick Rubin,2023,"Nonfiction, Art, Music, Philosophy, Self Help,...",amazon.com/Creative-Act-Way-Being/dp/059365288...
73,74,My First Library : Boxset of 10 Board Books fo...,16.74,4.6,Not available,2018,Childrens,amazon.com/My-First-Library-Boxset-Board/dp/93...
74,75,"Forever Strong: A New, Science-Based Strategy ...",20.63,4.6,Gabrielle Lyon,2023,"Health, Nonfiction, Nutrition, Fitness, Self H...",amazon.com/Forever-Strong-Science-Based-Strate...
76,77,Demon Copperhead: A Pulitzer Prize Winner,19.50,4.6,Barbara Kingsolver,2022,Fiction,amazon.com/Demon-Copperhead-Novel-Barbara-King...
77,78,Israel: A Simple Guide to the Most Misundersto...,15.59,4.7,Noa Tishby,2021,"Nonfiction, History, Politics, Israel, Jewish,...",amazon.com/Israel-Simple-Guide-Misunderstood-C...
78,79,Remarkably Bright Creatures: A Read with Jenna...,15.99,4.6,Shelby Van Pelt,2024,Fiction,amazon.com/Remarkably-Bright-Creatures-Shelby-...
79,80,Harry Potter Paperback Box Set (Books 1-7),45.22,4.9,J.K. Rowling,2014,"Childrens, Young Adult, Fantasy, Science Ficti...",amazon.com/Harry-Potter-Paperback-Box-Books/dp...
80,81,Just Because,12.69,4.6,Matthew McConaughey,2023,"Picture Books, Childrens, Fiction",amazon.com/Just-Because-Matthew-McConaughey/dp...
85,86,Love Comes First,17.99,NaN,Emily Giffin,2016,"Fiction, Romance, Contemporary, Audiobook, Adu...",amazon.com/Love-Comes-First-Jenna-Hager/dp/031...
86,87,The Ballad of Songbirds and Snakes (A Hunger G...,15.79,4.6,Suzanne Collins,2020,"Adventure, War, Science Fiction, Romance, Acti...",amazon.com/Ballad-Songbirds-Snakes-Hunger-Game...
87,88,A Court of Wings and Ruin (A Court of Thorns a...,11.56,4.8,Sarah J. Maas,2017,Fantasy,amazon.com/Court-Wings-Ruin-Thorns-Roses/dp/16...
88,89,The Shadow Work Journal 2nd Edition: a Guide t...,18.46,4.7,Keila Shaheen,2023,Self Help,amazon.com/Shadow-Work-Journal-2nd-Integrate/d...
89,90,Harry Potter and the Prisoner of Azkaban (Harr...,25.97,4.9,J.K. Rowling,1999,Fantasy,amazon.com/Harry-Potter-Prisoner-Azkaban-MinaL...
93,94,Percy Jackson and the Olympians: The Chalice o...,15.63,4.7,Rick Riordan,2023,"Fantasy, Adventure, Mythology",amazon.com/Percy-Jackson-Olympians-Chalice-God...
95,96,First Little Readers Parent Pack: Guided Readi...,11.40,4.7,Deborah Schecter,2010,Nonfiction,amazon.com/First-Little-Readers-Parent-Pack/dp...
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...
98,99,"I'm Dead, Now What?: Important Information Abo...",12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...

In [13]:
merged_subsets = pd.concat([subset1, subset2])

In [14]:
merged_subsets

,Rank,book title,book price,rating,author,year of publication,genre,url
0,1,"Iron Flame (The Empyrean, 2)",18.42,4.1,Rebecca Yarros,2023,Fantasy Romance,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
1,2,The Woman in Me,20.93,4.5,Britney Spears,2023,Memoir,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
2,3,My Name Is Barbra,31.50,4.5,Barbra Streisand,2023,Autobiography,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
3,4,"Friends, Lovers, and the Big Terrible Thing: A...",23.99,4.4,Matthew Perry,2023,Memoir,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
4,5,How to Catch a Turkey,5.65,4.8,Adam Wallace,2018,"Childrens, Fiction",amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...
...,...,...,...,...,...,...,...,...
89,90,Harry Potter and the Prisoner of Azkaban (Harr...,25.97,4.9,J.K. Rowling,1999,Fantasy,amazon.com/Harry-Potter-Prisoner-Azkaban-MinaL...
93,94,Percy Jackson and the Olympians: The Chalice o...,15.63,4.7,Rick Riordan,2023,"Fantasy, Adventure, Mythology",amazon.com/Percy-Jackson-Olympians-Chalice-God...
95,96,First Little Readers Parent Pack: Guided Readi...,11.40,4.7,Deborah Schecter,2010,Nonfiction,amazon.com/First-Little-Readers-Parent-Pack/dp...
97,98,"The Wager: A Tale of Shipwreck, Mutiny and Murder",15.30,4.5,David Grann,2023,Nonfiction,amazon.com/Wager-Tale-Shipwreck-Mutiny-Murder/...
98,99,"I'm Dead, Now What?: Important Information Abo...",12.99,4.6,Peter Pauper Press,2015,Nonfiction,amazon.com/Important-Information-Belongings-Bu...

In [15]:
sorted_df = df.sort_values(by='book price', ascending=False)

In [18]:
#Transpose df
transpose_df = df.head(10).T

In [17]:
transpose_df

,0,1,2,3,4,5,6,7,8,9
Rank,1,2,3,4,5,6,7,8,9,10
book title,"Iron Flame (The Empyrean, 2)",The Woman in Me,My Name Is Barbra,"Friends, Lovers, and the Big Terrible Thing: A...",How to Catch a Turkey,"Fourth Wing (The Empyrean, 1)",Unwoke: How to Defeat Cultural Marxism in America,No Brainer (Diary of a Wimpy Kid Book 18),Killers of the Flower Moon: The Osage Murders ...,All the Light We Cannot See: A Novel
book price,18.42,20.93,31.5,23.99,5.65,16.99,27.43,8.55,9.86,11.98
rating,4.1,4.5,4.5,4.4,4.8,4.8,4.3,4.8,4.4,4.5
author,Rebecca Yarros,Britney Spears,Barbra Streisand,Matthew Perry,Adam Wallace,Rebecca Yarros,Unknown,Jeff Kinney,David Grann,Anthony Doerr
year of publication,2023,2023,2023,2023,2018,2023,2023,2023,2017,2014
genre,Fantasy Romance,Memoir,Autobiography,Memoir,"Childrens, Fiction",Fantasy,"Nonfiction, Politics","Humor, Middle Grade","Nonfiction, True Crime",Historical Fiction
url,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...,amazon.com/Woman-Me-Britney-Spears/dp/16680090...,amazon.com/My-Name-Barbra-Streisand/dp/0525429...,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...,amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...,amazon.com/Fourth-Wing-Empyrean-Rebecca-Yarros...,amazon.com/Unwoke-Defeat-Cultural-Marxism-Amer...,amazon.com/Brainer-Diary-Wimpy-Kid-Book/dp/141...,amazon.com/Killers-Flower-Moon-Osage-Murders/d...,amazon.com/All-Light-We-Cannot-See/dp/15011732...

In [21]:
melt_df = df.head(5).melt(id_vars=["book title"])

In [22]:
melt_df

,book title,variable,value
0,"Iron Flame (The Empyrean, 2)",Rank,1
1,The Woman in Me,Rank,2
2,My Name Is Barbra,Rank,3
3,"Friends, Lovers, and the Big Terrible Thing: A...",Rank,4
4,How to Catch a Turkey,Rank,5
5,"Iron Flame (The Empyrean, 2)",book price,18.42
6,The Woman in Me,book price,20.93
7,My Name Is Barbra,book price,31.5
8,"Friends, Lovers, and the Big Terrible Thing: A...",book price,23.99
9,How to Catch a Turkey,book price,5.65
10,"Iron Flame (The Empyrean, 2)",rating,4.1
11,The Woman in Me,rating,4.5
12,My Name Is Barbra,rating,4.5
13,"Friends, Lovers, and the Big Terrible Thing: A...",rating,4.4
14,How to Catch a Turkey,rating,4.8
15,"Iron Flame (The Empyrean, 2)",author,Rebecca Yarros
16,The Woman in Me,author,Britney Spears
17,My Name Is Barbra,author,Barbra Streisand
18,"Friends, Lovers, and the Big Terrible Thing: A...",author,Matthew Perry
19,How to Catch a Turkey,author,Adam Wallace
20,"Iron Flame (The Empyrean, 2)",year of publication,2023
21,The Woman in Me,year of publication,2023
22,My Name Is Barbra,year of publication,2023
23,"Friends, Lovers, and the Big Terrible Thing: A...",year of publication,2023
24,How to Catch a Turkey,year of publication,2018
25,"Iron Flame (The Empyrean, 2)",genre,Fantasy Romance
26,The Woman in Me,genre,Memoir
27,My Name Is Barbra,genre,Autobiography
28,"Friends, Lovers, and the Big Terrible Thing: A...",genre,Memoir
29,How to Catch a Turkey,genre,"Childrens, Fiction"
30,"Iron Flame (The Empyrean, 2)",url,amazon.com/Iron-Flame-Empyrean-Rebecca-Yarros/...
31,The Woman in Me,url,amazon.com/Woman-Me-Britney-Spears/dp/16680090...
32,My Name Is Barbra,url,amazon.com/My-Name-Barbra-Streisand/dp/0525429...
33,"Friends, Lovers, and the Big Terrible Thing: A...",url,amazon.com/Friends-Lovers-Big-Terrible-Thing/d...
34,How to Catch a Turkey,url,amazon.com/How-Catch-Turkey-Adam-Wallace/dp/14...

In [25]:
subset3 = df[[  'book title']]
subset4 = df[['genre']]

In [28]:
merged_subsets2 = pd.concat([subset3, subset4], axis=1)

In [29]:
merged_subsets2

,book title,genre
0,"Iron Flame (The Empyrean, 2)",Fantasy Romance
1,The Woman in Me,Memoir
2,My Name Is Barbra,Autobiography
3,"Friends, Lovers, and the Big Terrible Thing: A...",Memoir
4,How to Catch a Turkey,"Childrens, Fiction"
...,...,...
95,First Little Readers Parent Pack: Guided Readi...,Nonfiction
96,Hatchet,"young adult novel, adventure novel, survival ..."
97,"The Wager: A Tale of Shipwreck, Mutiny and Murder",Nonfiction
98,"I'm Dead, Now What?: Important Information Abo...",Nonfiction
99,The Wonky Donkey,"Childrens, Picture Books"